services:
    # TODO: Specity image name (include versioning)
    main:
        build: .
        ports:
            - "8000:8000"
        environment:
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - USER_EMAIL=${USER_EMAIL}
            - USER_PASSWORD=${USER_PASSWORD}
            - EMAIL_NOTIFY_TO=${EMAIL_NOTIFY_TO}
